#!/bin/bash

set_correct_hostname() {
    # Fix hostname name
    domain=$(sudo yunohost domain list --output-as plain|head -1)
    if [ -n "$domain" ] && [ ! "hostnamectl --static | grep '\.'" ]; then
        sudo hostnamectl --static set-hostname "${domain}"
        sudo hostnamectl --transient set-hostname "${domain}"
        sudo hostnamectl --pretty set-hostname "La Brique InterNet (${domain})"

        if ! grep -q "127.0.0.1 ${domain}" /etc/hosts; then
            echo "127.0.0.1 $domain" | sudo tee -a /etc/hosts
        fi
        if ! grep -q "::1 ${domain}" /etc/hosts; then
            echo "::1 $domain" | sudo tee -a /etc/hosts
        fi
    fi
}
