#!/bin/bash

# Fix hostname and configure hosts
set_correct_hostname() {
    domain=$(sudo yunohost domain list | sed -n '2p' | sed 's/  - //')
    if [ -n "$domain" ] && ! hostnamectl --static | grep -q '\.'; then
        sudo hostnamectl --static set-hostname "${domain}"
        sudo hostnamectl --transient set-hostname "${domain}"
        sudo hostnamectl --pretty set-hostname "La Brique InterNet (${domain})"

        if ! grep -q "127.0.0.1 ${domain}" /etc/hosts; then
            echo "127.0.0.1 $domain" | sudo tee -a /etc/hosts
        fi
        if ! grep -q "::1 ${domain}" /etc/hosts; then
            echo "::1 $domain" | sudo tee -a /etc/hosts
        fi
    fi
}
