#!/bin/bash

source src/env
source src/helpers
source src/commands

set_doctorcube_version "${_LATESTVERSION}"

# Adds labriqueinternet app list
fetch_labriqueinternet_applist

# Sets a correct hostname based on the first Yunohost domain
if has_incorrect_hostname; then
  fix_hostname
fi

# Removes testing kernel 4.* bugged with Olimex network cards
if is_olinux_board && has_testing_kernel; then
  remove_testing_kernel
fi

# Updates the decryption web interface and rebuilds the initramfs
if has_encryptedfs && ! compare_decryption_webinterface_version latest; then
  update_decryption_webinterface latest
fi

exit 0
