#!/bin/bash

source src/env
source src/helpers
source src/commands

set_doctorcube_version "${_LATESTVERSION}"

# Adds labriqueinternet app list
if ! has_labriqueinternet_applist; then
  fetch_labriqueinternet_applist
fi

# Sets a correct hostname based on the first Yunohost domain
if ! has_correct_hostname; then
  fix_hostname
fi

# Removes testing kernel 4.* bugged with Olimex network cards
if is_olinux_board && has_testing_kernel; then
  remove_testing_kernel
fi

# The filesystem is encrypted
if has_encryptedfs; then

  # Updates the decryption web interface and rebuilds the initramfs
  # Please also update the sha in upgrade script...
  decryption_webinterface_version=d2a948cce56aaab014be9e27848a64c3a8db0832
  if ! compare_decryption_webinterface_version "${decryption_webinterface_version}"; then
    update_decryption_webinterface "${decryption_webinterface_version}"
  fi
fi

exit 0
