#!/bin/bash

# TODO check that we only do this on arm board to avoid people installing it on something else

set -xe

sudo yunohost app setting doctorcube version -v "0.1"

sudo yunohost app fetchlist -n labriqueinternet -u https://labriqueinter.net/apps/labriqueinternet.json

KERNEL_VERSION=$(uname -r)

for i in /etc/apt/sources.list.d/testing.list /etc/apt/sources.list.d/backports.list /etc/apt/preferences.d/kernel-testing /etc/apt/preferences.d/kernel-backports; do
    [ -e $i ] && sudo rm -f $i
done

echo "linux-image-$KERNEL_VERSION linux-image-$KERNEL_VERSION/prerm/removing-running-kernel-$KERNEL_VERSION boolean false" | sudo debconf-set-selections

DEBIAN_FRONTEND=noninteractive sudo apt-get remove -y --force-yes --purge linux-image-4* flash-kernel u-boot-tools u-boot-sunxi


if [ -f /etc/crypttab ] ; then
  sudo su root -c "echo 'LINUX_KERNEL_CMDLINE=\"console=ttyS2 hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x720p60 root=/dev/mapper/root cryptopts=target=root,source=/dev/mmcblk0p2,cipher=aes-xts-plain64,size=256,hash=sha1 rootwait sunxi_ve_mem_reserve=0 sunxi_g2d_mem_reserve=0 sunxi_no_mali_mem_reserve sunxi_fb_mem_reserve=0 panic=10 loglevel=6 consoleblank=0\"' > /etc/default/flash-kernel"
else
  sudo su root -c "echo 'LINUX_KERNEL_CMDLINE=\"console=ttyS1 hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x720p60 root=/dev/mmcblk0p1 rootwait sunxi_ve_mem_reserve=0 sunxi_g2d_mem_reserve=0 sunxi_no_mali_mem_reserve sunxi_fb_mem_reserve=0 panic=10 loglevel=6 consoleblank=0\"' > /etc/default/flash-kernel"
fi

sudo apt-get clean
sudo apt-get update
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes linux-image-armmp flash-kernel u-boot-sunxi u-boot-tools
sudo update-initramfs -k all -u
