#!/bin/bash

source src/env
source src/helpers
source src/commands

version=$_CURRENTVERSION

info "Current version of DoctorCube is ${version}"
info "Latest version of DoctorCube is ${_LATESTVERSION}"

if [ "${version}" = "${_LATESTVERSION}" ]; then
  info "Up-to-date, nothing to do"
  exit 0
fi

info "Upgrading..."

# 0.1 -> 0.2.1
if [ "${version}" = 0.1 ]; then

  # The hostname should not be a fake one like "olinux"
  if ! has_correct_hostname; then
    fix_hostname
  fi

  version=0.2.1
  set_doctorcube_version "${version}"
fi

# 0.2 -> 0.2.1
if [ "${version}" = 0.2 ]; then

  # The hostname was not correctly set in the case of only one single domain
  if ! has_correct_hostname; then
    fix_hostname
  fi

  version=0.2.1
  set_doctorcube_version "${version}"
fi

# 0.2.1 -> 0.3
if [ "${version}" = 0.2.1 ]; then
  if has_encryptedfs; then

    # The testing kernel was not correctly removed in the case of an
    # encrypted filesystem
    if is_olinux_board && has_testing_kernel; then
      remove_testing_kernel
    fi

    # Fixes a security issue (removing eval commands) and some minor bugs
    # Please also update the sha in install script...
    decryption_webinterface_version=d2a948cce56aaab014be9e27848a64c3a8db0832
    if ! compare_decryption_webinterface_version "${decryption_webinterface_version}"; then
      update_decryption_webinterface "${decryption_webinterface_version}"
    fi
  fi

  version=0.3
  set_doctorcube_version "${version}"
fi

info "Upgrading done"

exit 0
